# Generated by Django 3.2.6 on 2021-08-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeCrud', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
